In [1]:
data1 = '안녕 나는 오늘 힘들어'.split()
data2 = '안녕 못해 나는 지금 너무 힘들어'.split()

In [3]:
un = set(data1) | set(data2)
un

{'나는', '너무', '못해', '안녕', '오늘', '지금', '힘들어'}

In [4]:
intd = set(data1) & set(data2)
intd

{'나는', '안녕', '힘들어'}

In [5]:
j = len(intd) / len(un)
j

0.42857142857142855

In [8]:
data1 = '안녕 나는 오늘 힘들어.'
data2 = '안녕 못해 나는 지금 너무 힘들어'

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

t_v = TfidfVectorizer()
m_data = t_v.fit_transform([data1, data2])
m_data.toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087],
       [0.33471228, 0.47042643, 0.47042643, 0.33471228, 0.        ,
        0.47042643, 0.33471228]])

In [14]:
t_v.vocabulary_

{'안녕': 3, '나는': 0, '오늘': 4, '힘들어': 6, '못해': 2, '지금': 5, '너무': 1}

In [15]:
idf = t_v.idf_
idf

array([1.        , 1.40546511, 1.40546511, 1.        , 1.40546511,
       1.40546511, 1.        ])

In [18]:
from sklearn.metrics import jaccard_score  # 입력이 0과 1사이의 값이어야 함.
import numpy as np
jaccard_score(np.array([0, 1, 0, 0]), np.array([0, 1, 1, 2]), average = None)

array([0.33333333, 0.5       , 0.        ])

In [19]:
def f(A, B):
    return np.sqrt(np.sum((A - B) ** 2))

In [21]:
A = np.array([0, 1, 2, 3, 4])
B = np.array([1, 0, 1, 2, 3])
f(A, B)

2.23606797749979

In [22]:
from sklearn.metrics import euclidean_distances
euclidean_distances(m_data[0:1], m_data[1:2])

array([[1.0486415]])

In [26]:
def e_f(m):
    return m / np.sum(m)

e_data = e_f(m_data)
e_f(m_data).toarray()

array([[0.10211209, 0.        , 0.        , 0.10211209, 0.14351497,
        0.        , 0.10211209],
       [0.07623595, 0.10714697, 0.10714697, 0.07623595, 0.        ,
        0.10714697, 0.07623595]])

In [27]:
euclidean_distances(e_data[0:1], e_data[1:2])

array([[0.23884449]])

In [28]:
def f(A, B):
    return np.sum(abs(A - B))

In [29]:
f(A, B)  # 거리이기 때문에 값이 클수록 유사도가 떨어짐

5

In [32]:
from sklearn.metrics.pairwise import manhattan_distances
euclidean_distances(m_data[0:1], m_data[1:2]), manhattan_distances(m_data[0:1], m_data[1:2])

(array([[1.0486415]]), array([[2.38220441]]))

In [33]:
euclidean_distances(e_data[0:1], e_data[1:2]), manhattan_distances(e_data[0:1], e_data[1:2])

(array([[0.23884449]]), array([[0.54258429]]))

In [38]:
data3 = '나는 너무 즐거워 '
m_data2 = t_v.fit_transform([data1, data2, data3])
e_data2 = e_f(m_data2)

In [39]:
euclidean_distances(m_data2[0:1], m_data2[1:2]), euclidean_distances(m_data2[1:2], m_data2[2:3])

(array([[1.02891385]]), array([[1.15714912]]))

In [40]:
euclidean_distances(e_data2[0:1], e_data2[1:2]), euclidean_distances(e_data2[1:2], e_data2[2:3])

(array([[0.16949987]]), array([[0.19062493]]))

In [42]:
 manhattan_distances(m_data2[0:1], m_data2[1:2]),  manhattan_distances(m_data2[1:2], m_data2[2:3])

(array([[2.28685493]]), array([[2.76734191]]))

In [43]:
 manhattan_distances(e_data2[0:1], e_data2[1:2]),  manhattan_distances(e_data2[1:2], e_data2[2:3])

(array([[0.37672893]]), array([[0.45588277]]))